schema_version = "1.0.0"

id = "tiny_backup"
version = "1.0.1"
name = "Tiny Backup"
tagline = "A minimalistic backup solution"
maintainer = "Thane5"
type = "add-on"
website = "https://github.com/Thane5/blender-tiny-backup"
tags = ["System"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-2.0-or-later",
]

[permissions]
files = "Save backups on disk"